### ISSUE TITLE
MySQL Errors with latest version

### ISSUE THREAD

**Issue by FreakySt0rm** [GameConnect/SourceBans#40]
Hi, I've downloaded and installed the latest version from GitHub, installation went perfectly, but now I can't access sm_admin even though I've set up myself as a server admin, and I'm getting these lines in the SourceMod logs:
L 04/04/2014 - 10:58:24: [sourcebans.smx] Failed to query database. (Unknown column 'ip' in 'where clause')

L 04/04/2014 - 10:58:29: [sourcebans.smx] Failed to query database. (Cannot add or update a child row: a foreign key constraint fails (`sourcemod`.`sb_actions`, CONSTRAINT `action_server` FOREIGN KEY (`server_id`) REFERENCES `sb_servers` (`id`) ON DELETE CASCADE))

Am I doing anything wrong, or is this a known issue?

Many thanks!

FreakySt0rm - St0rm.net Gaming

**Comment by WildCard65** [comment]
@peace-maker can you close this issue?
