### ISSUE TITLE
Error #40 again...

### ISSUE THREAD

**Issue by iraqiboy90** [GameConnect/SourceBans#55]
Hello

I've been trying to install this but I always get:
[sourcebans.smx] Failed to query database. (Unknown column 'ip' in 'where clause')

The fix which was supposed to be applied at 11.Jule isnt really applied everywhere.
The sourceban.sp file is for one isnt updated.

So here is what I did:
(While server is shutdown)
1. Installed/Configured the webpanel
2. Uploaded the Game folder to the server
3. Add the server on webpanel
(now turning server on)
4. Looking at the logs: Failed to query database. (Unknown column 'ip' in 'where clause')
(shutdown the server)
5. Delete all Game files on servers
6. Drop all DB
7. Remove all webpanel files.
8. Reupload the webpanel files
9. Modified the original sourceban.sp file, changing "ip" to "host", then upload the Game folder to the game server.
10. Install & config webpanel & add server
(Turning server on)
11. Looking at the logs: Failed to query database. (Unknown column 'ip' in 'where clause')

So, what is missing?

**Comment by WildCard65** [comment]
The webpanel runs things on the server via rcon. It queries the server VIA a UDP Port that the server opens(I believe it uses the port number passed to -port, or default if not passed which is 27015). The rcon stuff is done via TCP as the webpanel needs a response and needs to know if it needs to resend the rcon stuff or if GS needs to resend response.

**Comment by iraqiboy90** [comment]
:+1:

**Comment by ErikMinekus** [comment]
Fixed in #46.
