### ISSUE TITLE
Issue: Where is the developer?

### ISSUE THREAD

**Issue by iraqiboy90** [GameConnect/SourceBans#64]
look at the title

**Comment by Sarabveer** [comment]
What developer?

**Comment by iraqiboy90** [comment]
One that was busy for 6 months? Or is this project actually dead? Which one is it

**Comment by Bubka3** [comment]
The project is as good as dead as far as the original developers are concerned.

**Comment by iraqiboy90** [comment]
that's a shame :(

**Comment by WildCard65** [comment]
Well peacemaker just merged fix for #40

**Comment by Bubka3** [comment]
That was just a request from me. I don't believe he is working on the plugin atm.

**Comment by ErikMinekus** [comment]
I am here.
