### ISSUE TITLE
Sourcebans and mysql admin

### ISSUE THREAD

**Issue by romkazor** [GameConnect/SourceBans#73]
Hello. Sorry for my english.
Can sourcebans work with mysql admin without any text file: admins.cfg, admin_groups.cfg like this https://wiki.alliedmods.net/SQL_Admins_(SourceMod)
Thanks

**Comment by vince52** [comment]
Hello,
yes it can.
Your welcome

**Comment by peace-maker** [comment]
Yes, it already does. You could set "BackupConfigs" to 0 in your sourcebans.cfg if you still use the old 1.4.11 plugin.
