### ISSUE TITLE
PHP7 Compatibility

### ISSUE THREAD

**Issue by rafalolszewskii** [GameConnect/SourceBans#85]
To make it clear, SB **is not** compatibile with PHP7 right ? I ran on to critical issue which is steam authentication not working (not storing the session after steam authentication was done).

**Comment by Sarabveer** [comment]
This version of SourceBans is under dev, and you should expect bugs.

**Comment by ErikMinekus** [comment]
This version is compatible with PHP 7, however none of the official SourceBans versions have Steam authentication, so you're probably talking some other version that we don't support.
