### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by lucky84** [GameConnect/SourceBans#91]
Hi Erik,

i wanted to test this, but i get this error

> Fatal error: Uncaught Error: Call to undefined function mysql_get_client_info() in .../sourcebans/install/index.php:22 Stack trace: #0 {main} thrown in .../sourcebans/install/index.php on line 22

i use this version -> https://forums.alliedmods.net/showthread.php?t=219657

**Comment by ppalex7** [comment]
mysql_get_client_info was removed in php 7.0. i suggest your to try it with older php version.

**Comment by lucky84** [comment]
ah ok, now it works, thank you :)
