### ISSUE TITLE
Ban Imports

### ISSUE THREAD

**Issue by lucky84** [GameConnect/SourceBans#92]
Hi,

have imported bans, but player names are not set.

![Screenshot 2020-10-01 195617](https://user-images.githubusercontent.com/4884795/94845587-32a3eb00-0420-11eb-8f26-958414cd1d86.png)

**Comment by ErikMinekus** [comment]
`banned_user.cfg` looks like this:
```
banid 0 STEAM_0:1:23456
```
There are no player names to import.

**Comment by lucky84** [comment]
sourcebans will not get the names from Steam?

**Comment by zapy85** [comment]
> sourcebans will not get the names from Steam?

No, as it is not necessary information, steamid is the important part.
When baning ingame with the sourcebans ban menu or commands it will write the name in use by the player on the server.

**Comment by lucky84** [comment]
my mistake, i found this in Version 1.4.11

![Screenshot 2020-10-03 153747](https://user-images.githubusercontent.com/4884795/94993084-bd0a5d00-058e-11eb-9dfb-cb2e583e81aa.png)

Version 2.0.0-dev does not have the function.
